### ISSUE TITLE
提取特侦

### ISSUE THREAD

**Issue by Poly00777** [QiuZYin/CICFlowMeter#1]
这个好像不能提取特征吧

**Comment by QiuZYin** [comment]
你好，代码已修改，可以再试试。

**Comment by Poly00777** [comment]
谢谢回复，现在有些pcap文件（从其他网站下载的pcap包或者自己抓取的pcap包）可以提取，但是Thursday-WorkingHours.pcap | 2019-09-10 16:46 | 7.7G和UNSW-NB15 （大小2G）数据集没有输出，您是否尝试过cicids 2017的Thursday-WorkingHours.pcap提取？还是因为文件太大导致没有输出的原因？



<br class="Apple-interchange-newline">
</body>
</html>[Tuesday-WorkingHours.pcap](http://205.174.165.80/CICDataset/CIC-IDS-2017/Dataset/PCAPs/Tuesday-WorkingHours.pcap)	2019-09-10 18:18	10G

**Comment by QiuZYin** [comment]
你好，cicids 2017的数据不是标准的PCAP格式，你可以输出看看，就能明白了。
为了解决这个问题，我是用wireshark将它重新保存了一下，就变成标准PCAP格式了。
其实这里我也很困惑，为什么wireshark可以正确读取cicids 2017。
最后还有一点就是，官网下的cicids 2017是以大端模式保存的，用wireshark重新保存之后，PCAP Header的Magic字段是0x4dc3b2a1，也就是以小端模式存储，然而实际上，Packet Data部分任然是以大端模式存储，这一点我在PacketReader.py文件的28-31行也有说明。

UNSW-NB15这个数据集我没有用过，所以不太清楚，你可以用wireshark重新保存一下，再看看能不能提取。

**Comment by Poly00777** [comment]
非常感谢，重新保存会报错，我分割一下就可以提取特征了

**Comment by QiuZYin** [comment]
重新保存会报错是不是因为内存大小不够？

请问分割是怎么操作的？

**Comment by Poly00777** [comment]
用wireshark另存为，保存到后边会弹窗显示以下内容，
The capture file "wu.pcap" appears to be damaged orcorrupt.
(pcap: File has 1466369542-byte packet, bigger thanmaximum of 262144)
尽管报错依然会有文件保存，不过保存的内容少一些，但是特征提取依然会有报错
  File "D:\Desktop\github\CICFlowMeter-main\CICFlowMeter-main\PacketReader.py", line 128, in getIpv4Info
    payload = packetTCP[tcpHeadLen:]
MemoryError
如果直接用原pcap文件进行特征提取，也会报错
    packetData = self.pcapData[self.pcapPtr : self.pcapPtr + caplen]
MemoryError
分割用的wireshark 的菜单栏第一个文件-导出特定分组，左边选range 填上范围1-xxxxx，右边选择captured

**Comment by QiuZYin** [comment]
好的，非常感谢！

**Comment by Poly00777** [comment]
请问内存大小不够是如何解决的？还是说要分割成小文件

**Comment by QiuZYin** [comment]
我用的实验室服务器，内存有256G。

但是我用wireshark另存，也会出现和你相同的情况。
另存文件的大小比原文件小，不过数据包个数没有减少。

我之前也用过 SplitCap 这个工具重组会话流，但是它的切分结果和我的代码不同。

最近在找工作，好久没做这个实验了，有些东西记不太清了，不好意思。

**Comment by QiuZYin** [comment]
加个好友吧，QQ：577662673
之前一直都是我一个人在做这个，没人交流，好不容易遇到一个。
